version: '3'
services: 
    app:
      container_name: codebond-dep_app
      restart: always
      build: .
      volumes:
        - './:/app/'
      ports:
        - '8000:8000'
      links:
        - mongopassword_recover/?recover_code=7207f53bc80e0083e407d56d14953688b335cc78488bc4dcc6d9ee86264267df
      environment:
        googleId           : 1084112566139-r95aljn6sf2o0e9gi4179c07aq0iabrv.apps.googleusercontent.com
        googleSecret       : XUoyvv6FQxPXoeUA-6rl2njZ
        mongodbUrl         : mongodb://mongo:27017/codebond-dep_app
        sessionKey         : asdoksfovasodjaklfvoa
        cloudName          : codebond
        cloudKey           : 196393852738322
        cloudSecret        : QRNJNpqV0HVB7f8TjBbjOuzGjl8
        emailFrom          : codebond.cb@gmail.com
        googleGmailId      : 560125691479-u12f0gld7v2jte46vbqoc41iit2cd3si.apps.googleusercontent.com
        googleGmailSecret  : RIcNt-cZ2l07J6tRW99Dv0h9
        googleRefreshToken : 1/meRnxcghabkbEHJDl2SwjEeSui1I_ClYYba2GiuS3Gg
        googleAccessToken  : ya29.Glt0B3esCL-fNcfwyD56IlaT4_-IyVqy_8jvNIZ97i_HXG0AF0vBqxwrmUc7sJ6p-YVJXH-kKX3dt-wwEjTTL6Kbl46eyANvVJ_YUNX8XzTJtnYj9irLynXTaOTu
        emailTo            : saudchougle.sc@gmail.com
        jwtSecret          : hhsslarljkfajkibnbakjdsfjk2312
    mongo:
      container_name: mongo
      image: mongo
      restart: always
      ports:
        - '27017:27017'
   
